codeforkumamoto/covid19

- README.md
- #6 
- netlifyのURLを追記
- デプロイされるかの確認も
> netlifyのURLを追加

- layouts/default.vue
- close #20 
- #20 
- logo.svgじゃなく熊本用のlogo.pngに差し替え
> ローディング時の画像を差し替え

- nuxt.config.ts
- close #22 
- #22 
- 言語のリストから日本語以外を削除
> 日本語以外を一旦コメントアウト

- nuxt.config.ts
- #9 
- ogp:urlをnetlifyのものに。
- titleとかもdevであることが分かるように
> OGP設定でFBから怒られないように

- nuxt.config.ts
> OGP画像のURL修正忘れ

- nuxt.config.ts
OGP設定調整
- close #38 
- #0
- #0
- OGP設定調整
> OGP設定調整 #38

- nuxt.config.ts
> GoogleAnalytics設定

- components/SideNavigation.vue
- nuxt.config.ts
- close #44 
- ここにあるとおりに修正。 https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg
> 言語切り替えをオフにする

- README.md
- close #4 
- かっこよくなったOGP画像をREADMEに貼った
> READMEにOGP画像を同じものをセット

- assets/variables.scss
- components/TimeBarChart.vue
- components/TimeStackedBarChart.vue
- layouts/default.vue
- layouts/print.vue
- close #48
- greenという変数名自体を変更
- 変わらなかった部分は直接RGB値を修正
> 配色を熊本県旗の海老茶色に設定

- components/TimeStackedBarChart.vue
- close #51
- tooltipsについても先頭を無視させる
> 日別の検査数表示では初日のデータを非表示にする(tooltipも)

- layouts/default.vue
- close #54 
- close #0
- #0
- #0
- layouts/defaut.vue内のコード削除
- xxx
> head内に東京環境の記述があるのを削除

- README.md
> ステージング環境準備

- components/SideNavigation.vue
- close #66 
- 知事からのメッセージリンクをサイドバーから削除
> 知事からのメッセージはサイドバーから削除

- components/cards/TestedNumberCard.vue
- close #101 
- 検査実施数カードの見出しを修正
> 県検査分に熊本市を含まないことを明記

- components/SideNavigation.vue
- pages/about.vue
- close #104 
- close #105
- 県内有志が作成した旨をサイドバーに明記
- 行政のSNSリンクを削除し、製作者のリンクを掲載
> 製作者と行政と切り分け

- data/news.json
- close #109
- 「最新のお知らせ」を日付の降順に修正
- 「最新のお知らせ」の日付フォーマットを yyyy/mm/dd 似修正
> Fix #109 「最新のお知らせ」を見やすくする

- components/SideNavigation.vue
- close #91 
- close #0
- #0
- #0
- HTML修正
- CSS調整
> スマホ時ヘッダー表示の修正

- components/cards/ConfirmedCasesAttributesCard.vue
- components/cards/ConfirmedCasesDetailsCard.vue
- components/cards/ConfirmedCasesNumberCard.vue
- close #128
- タイトル通り。文字列を削除しただけ。
> 仮データの文言を削除

- data/news.json
- close #137 
- 古いお知らせを隠す（json上は残して、別のキーにする）
- 随時データ更新されているという説明にした
> Issue137 古いお知らせを隠して、随時データ更新されていると伝える

- README.md
- close #148
- close #149
- 画像差し替え
- リンク先変更
> READMEの画像差し替えと本家リポジトリへのリンク

- .github/CONTRIBUTING.md
- CONTRIBUTORS.md
> 貢献についての情報を更新

- components/TimeStackedBarChart.vue
- components/cards/ConfirmedCasesAttributesCard.vue
- components/cards/ConfirmedCasesNumberCard.vue
- components/cards/TelephoneAdvisoryReportsNumberCard.vue
- components/cards/TestedNumberCard.vue
- close #159 
- urlの追加
- 検査実施数はurlのプロパティがなかったので追加
- 検査陽性者の状況カードへの対応は保留(本家も出してないので)
> カードごとオープンデータリンクを復活

- components/ListItem.vue
- components/SideNavigation.vue
- close #132 
- #132 
- SideNavigation.vueに要素を追加
- ListItem.vueにisCioLinkのメソッドとスタイルの追加
変更前:
変更後:
> # 132 Add a link to GovernmentCIO

- pages/index.vue
- #167 
- （data.json自動化に向けて）discharges_summaryを削除。使ってないのにdata.jsonから抜くとエラーになるので。
> discharges_summaryを削除(使ってないのにdata.jsonから抜くとエラーになるので)

- components/SideNavigation.vue
- components/WhatsNew.vue
- pages/index.vue
> 相談手順を最新に更新

- components/DataTable.vue
- components/DataView.vue
- components/RemarksView.vue
- components/TimeBarChart.vue
- components/TimeStackedBarChart.vue
- components/cards/ConfirmedCasesAttributesCard.vue
- components/cards/ConfirmedCasesDetailsCard.vue
- components/cards/ConfirmedCasesNumberCard.vue
- components/cards/TestedNumberCard.vue
- package.json
- yarn.lock
- close #322 
- #0
- #0
- 愛知のソースを参考に
- CSSの調整は未了
> 注記(remark)を下部に

- package.json
- yarn.lock
- close #0
- close #0
- #313 
- xxxxxx
- xxx
> デプロイでlinqなくてエラーになったので

- components/DataSelector.vue
- close #0
- close #0
- #313
- xxxxxx
- xxx
> DataSelectorのエラー対応

- assets/locales/en.json
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
> syntax error

- components/ConfirmedCasesDetailsTable.vue
- close #375 
- close #0
- #0
- #0
- xxxxxx
- xxx
> 検査陽性者の状況を縦積みにする

- components/SideNavigation.vue
- close #368
- #0
- #0
- xxxxxx
- xxx
> 県HP内のコンテンツへリンクしているものは削除(古いからトップだけにする)
